'use strict';

var STATIC_ROOT  = 'src/server/static/autogenerated';
var SERVER_ROOT  = 'src/server/';
var CLIENT_ROOT  = 'src/client/';
var NPM_ROOT     = 'node_modules/';

module.exports = {

    environment: {
        livereload : false,
        minify     : true,
        uglify     : false,
        concat     : true,
        sourcemaps : true
    },

    project: {
        name: 'liveclean'
    }
};
